-- App-related selects
SELECT * FROM APP ;
SELECT * FROM APP_CONSTRUCTS ;

SELECT * FROM APP_DEPENDENCY;
SELECT * FROM APP_DEPENDENCY_REACHABLE_CONSTRUCT_IDS; 
SELECT * FROM APP_DEPENDENCY_TOUCH_POINTS; 

SELECT * FROM APP_GOAL_EXE;
SELECT * FROM APP_GOAL_EXE_CONFIGURATION;
SELECT * FROM APP_GOAL_EXE_SYSTEM_INFO;
SELECT * FROM APP_GOAL_EXE_SYSTEM_INFO;

SELECT * FROM APP_PATH ;
SELECT * FROM APP_PATH_PATH ;

SELECT * FROM APP_TRACE;

-- Bug-related selects
SELECT * FROM BUG ;
SELECT * FROM BUG_AFFECTED_LIBRARY; 
SELECT * FROM BUG_CONSTRUCT_CHANGE;

-- Library-related selects
SELECT * FROM LIB ;
SELECT * FROM LIB_CONSTRUCTS ;
SELECT * FROM LIB_PROPERTIES;

-- Cross-cutting selects
SELECT * FROM CONSTRUCT_ID ;
SELECT * FROM LIBRARY_ID ;
SELECT * FROM PROPERTY;